_target_: models.diffusions.sdes.VpSde
score_net:
  _target_: models.diffusions.networks.UNet2D
  sample_size: ${dataset.image_size}  # The target image resolution
  in_channels: 3  # The number of input channels, 3 for RGB images
  out_channels: 3  # The number of output channels
  layers_per_block: 3  # How many ResNet layers to use per UNet block
  block_out_channels: # The number of output channels for each UNet block
    - 128
    - 256
    - 256
    - 256
  down_block_types:
    - DownBlock2D  # A regular ResNet downsampling block
    - DownBlock2D
    - AttnDownBlock2D  # A ResNet downsampling block with spatial self-attention
    - AttnDownBlock2D
  up_block_types:
    - AttnUpBlock2D  # A ResNet upsampling block with spatial self-attention
    - AttnUpBlock2D
    - UpBlock2D  # A regular ResNet upsampling block
    - UpBlock2D
