train:
  _target_: data.datasets.generated.LIDSyntheticDataset
  size: 1000000
  distribution:
    _target_: data.distributions.Lollipop
    center_loc: [3.0, 3.0]
    radius: 1.0
    stick_end_loc: [1.5, 1.5]
    dot_loc: [0.0, 0.0]
    candy_ratio: 4
    stick_ratio: 2
    dot_ratio: 1


val:
  _target_: data.datasets.generated.LIDSyntheticDataset
  size: 1000
  distribution: ${dataset.train.distribution}


data_dim: 2
is_tabular: true
is_image: false
training_torch_data: ${dataset.train}
